arcoiris=("azul", "verde","rojo","amarillo")
print(arcoiris)
print("--longitud arcoiris--")
print(len(arcoiris))
animales=("pantera",20,"estatura",1.7)
print(animales)
print("elementos de la tupla")
print(animales[1])
reteros=("juan","ana","pedro")
y=list(reteros)
y[0]="polainas"
x=tuple(y)
print(x)
print("agregando elementos")
Nanimal=("body","chetos")
y=list(Nanimal)
y.append("tontolin")
otratupla= tuple(y)
print(otratupla)
print("uso de for e tuplas")
for elcolor in arcoiris:
    print(elcolor)